test build scripts

diff --git a/clogrc/clog.yaml b/clogrc/clog.yaml
--- a/clogrc/clog.yaml
+++ b/clogrc/clog.yaml
@@ -8,108 +8,63 @@
 #                      ⇓⇓⇓⇓⇓⇓⇓⇓⇓
 # ALL KEYS ARE    ⇒⇒  lowercase    ⇐⇐  only. THIS IS A VIPER SETTING.
 #                      ⇑⇑⇑⇑⇑⇑⇑⇑⇑
-### when clog starts it uses these config values to override clog defaults.
+# #############################################################################
+#                      __   _
+#   __   ___   _ _    / _| (_)  __ _
+#  / _| / _ \ | ' \  |  _| | | / _` |
+#  \__| \___/ |_||_| |_|   |_| \__, |
+#                              |___/
+# -----------------------------------------------------------------------------
 clog:
   # path to the yaml file defining release history - see semver package
   releases-path: "assets/data/releases.yaml"
 
-# --- shell snippets for this project -----------------------------------------
+# #############################################################################
+#               _                       _
+#   ||_  _ _   (_)  _ __   _ __   ___  | |_   ___
+#  (_-< | ' \  | | | '_ \ | '_ \ / -_) |  _| (_-<
+#  / _/ |_||_| |_| | .__/ | .__/ \___|  \__| /__/
+#   ||             |_|    |_|
+# -----------------------------------------------------------------------------
 snippets:
   # build control logic for this repo - all commands start with bc
+  # dev or prod rules:
+  #     default - always dev unless build: prod in bc-releases-yaml
+  #     rules
+  #       - build+deploy- if github_event=="create" then checkout to main
+  #       - prod deploy - main branch or empty(default) branch only
+  #       - prod deploy - main repo (not fork) only
+  #     override
+  #       - MAKE prod - forces production (and overrides MAKE dev)
+  #       - MAKE dev  - forces development
+  # clog bc-prod-logic-xx returns    "dev|prod"+"(reasonString)"
   bc-releases-yaml: yq -r '.clog."releases-path"' clogrc/clog.yaml
-  bc-is-dev-build: yq -r '.[0].build|select(.=="dev")' "$(clog bc-releases-yaml)"
-  bc-is-prod-build: yq -r '.[0].build|select(.=="prod")' "$(clog bc-releases-yaml)"
+  bc-main-repo: echo "metarex-media/www-metarex-media"
+  bc-prod-logic-build: |
+    do="$(yq -r '.[0].build|select(.=="prod")' "$(clog bc-releases-yaml)")"
+    [ -z "$do" ] && do="dev(from releases.yaml)" || do="prod(from releases.yaml)" 
+    # rules - ensure valid brach for workflow
+    [[ "create" == "$GITHUB_EVENT_NAME " ]] && git checkout main
+    # overrides always win - prod override strongest
+    clog Should MAKE "dev" && do="dev(forced by MAKE)"
+    clog Should MAKE "prod" && do="prod(forced by MAKE)"
+    echo "$do"
+  bc-prod-logic-deploy: |
+    do="$(yq -r '.[0].build|select(.=="prod")' "$(clog bc-releases-yaml)")"
+    [ -z "$do" ] && do="dev(from releases.yaml)" || do="prod(from releases.yaml)" 
+    # rules
+    [[ "create" == "$GITHUB_EVENT_NAME " ]] && git checkout main
+    [ -n "$(clog git branch)" ] && [[ "$(clog git branch)" != "main" ]] && do="dev(not main branch)"
+    [[ "$(clog bc-main-repo)" != "$(clog git repo)" ]] && do="dev(repo!=$(clog bc-main-repo))"
+    # overrides always win - prod override strongest
+    clog Should MAKE "dev" && do="dev(forced by MAKE)"
+    clog Should MAKE "prod" && do="prod(forced by MAKE)"
+    echo "$do"
   bc-wants-stage-flow:  yq -r '.[0].flow|select(.=="stage")' "$(clog bc-releases-yaml)"
   bc-wants-test-flow:  yq -r '.[0].flow|select(.=="test")' "$(clog bc-releases-yaml)"
   bc-wants-schedule-flow:  yq -r '.[0].flow|select(.=="schedule")' "$(clog bc-releases-yaml)"
-  bc-log-e: |
-    doProd="$1"
-    MSG="$2"
-    [ -z "$doProd" ] && clog Log -E "prod: $MSG - aborting" && exit 1
-    clog Log -W " dev: $MSG -- ignoring errors" && exit 0
-  bc-divider-string: eval "$clog Crayon";for i in {1..8};do DIV="$DIV$cW▬▬▬▬▬▬▬▬▬$cE|";done;echo "$DIV"
-  build-type: val="$(yq -r '.[0].build' "$(clog bc-releases-yaml)")""; 
-  should-stage: yq -r '.[0].version' "$(clog bc-releases-yaml)"|grep -oE 'stage'
-  prod-tag:  yq -r 'first(.[] | select(.build == "prod")) | .version' "$(clog bc-releases-yaml)"
-  build-hugo: |
-    eval "$(clog Crayon)"
-    isDev="$1";[ -n "$isDev" ]&&txt=" (${cE}development${cX})"
-    clog Log -I "$STEP.$(((s+=1))).⚒️  build$txt hugo →$cF kodata/"
-    [ ! -d content ] && clog Log -E "$STEP.$(((s+=1))). no content/ folder" && exit 1
-    clog Log -I "$STEP.$(((s+=1))). purge$cF kodata/$cX, build site"
-    rm -rf kodata/*
-    opt=""
-    [[ "dev" == "$(clog build-type)" ]]  && opt="$opt --buildDrafts --buildFuture --buildExpired"
-    clog Log -I "$STEP.$(((s+=1))). build hugo →${cF}kodata/$cC $opt"
-    hugo build --minify --logLevel info $opt
-  build-podserver: |
-    eval "$(clog Crayon)"
-    helper="core/sh/help-golang.sh"    # build helpers
-    eval "$(clog Cat $helper)"
-    clog Log -I "$STEP.$(((s+=1))).⚒️  build-golang $cC $PROJECT $cX using clog's$cF $help"
-    clog Log -I "$STEP.$(((s+=1))). build-podserver →$cF tmp/"
-    fGoBuild tmp/podserver-amd-lnx     linux   amd64
-    fGoBuild tmp/podserver-arm-lnx     linux   arm64
-    fGoBuild tmp/podserver-arm-mac     darwin  arm64
-    [ $? -eq 0 ] && clog Log -I "stand-alone podserver exe built to$cF tmp/"
-  build-ko: |
-    eval "$(clog Crayon)"
-    isDev="$1";[ -n "$isDev" ]&&txt=" (${cE}development${cX})"&&devtag="-dev"
-    [ -z "$DOCKER_NS" ] && DOCKER_NS="mrmxf"
-    clog Log -I "$STEP.$(((s+=1))).⚒️  build ko →$cU hub.docker.com/$DOCKER_NS$cX"
-
-    tag1="$(clog git tag ref)$devtag"         # 1.2.3 or 1.2.3-stage or 1.2.3-stage-dev
-    [ -n "$(clog should-stage)" ]&& stagetag="-stage"
-    tag2="latest$stagetag$devtag"  # latest or latest-stage latest-dev latest-stage-dev
-
-    # config is in .ko.yaml
-    # use the default docker repo unless told otherwise
-    [ -z "$KO_DOCKER_REPO" ] && KO_DOCKER_REPO="$DOCKER_NS"
-    export KO_DOCKER_REPO
-    export KO_CONFIG_PATH=".ko.yaml"
-    # ensure that dates are added to the images
-    export KO_DATA_DATE_EPOCH=$(git log -1 --format='%ct')
-    ko build --base-import-paths --tags "$tag1" --tags "$tag2" .
-    if [ $? -gt 0 ]; then
-      msg="ko build failed $cE $PROJECT$cX:$cW$tag1$cX and ${cW}$tag2"
-      clog Log -E "$msg"
-      printf "$msg" > /tmp/clog-notify
-    else    
-      msg="multi-arch ko build$cF $PROJECT$cX:$cW$tag1$cX and ${cW}$tag2"
-      clog Log -S "$msg"
-      printf "$msg" > /tmp/clog-notify
-    fi
-
-  build: |
-    # all builds use data from releases.yaml unless: clog build MAKE "hugo ko prod"
-    export MAKE="hugo podserver ko"
-    [ -n "$1" ] && [ -n "$2" ] && MAKE="$2"
-    doPROD="$(clog bc-is-prod-build)"
-    clog Should MAKE "prod" && doPROD="prod(cli override)"
-
-    eval "$(clog Source project config)\n $(clog Crayon)" # setting & highlights
-    MSG="$cS$doPROD$cX"
-    [ -z "$doPROD" ] && MSG="(${cE}development$cX)"
-
-    clog Log -I  "🤖 build $MSG$cS $PROJECT$cX components: $cC $MAKE"
-
-    ERR=0
-    clog Check pre-build; ERR=$((ERR+$?))
-    clog Check build;     ERR=$((ERR+$?))
-    if [ $ERR -gt 0 ]; then
-       clog bc-log-e "$doPROD" "check produced errors" || exit 1; #abort if PROD
-    fi
-
-    clog Log -I  "$(clog bc-divider-string)"
-
-    #refactor from here
-    
-    isDev="Y"; [ -n "$doPROD" ] && isDev=""
-    export STEP=0
-    ((STEP++));clog Should MAKE "hugo"      && clog build-hugo      "isDev" && clog Log -I "$DIV" || exit 1
-    ((STEP++));clog Should MAKE "podserver" && clog build-podserver "isDev" && clog Log -I "$DIV" || exit 1
-    ((STEP++));clog Should MAKE "ko"        && clog build-ko        "isDev" && clog Log -I "$DIV" || exit 1
-    clog Log -I "   build complete"
+  bc-logs-hr: eval "$(clog Crayon)";for i in {1..8};do HR="$HR\e[09${i}m▬▬▬▬▬▬▬▬▬$cE|";done;printf "$HR$cX\n"
+  # ---------------------------------------------------------------------------------------------------------
   watch: hugo server --port=1313 --logLevel debug --buildDrafts --buildFuture --buildExpired --cleanDestinationDir
   git:
     # get the target version for this project from releases.yaml
@@ -147,6 +102,97 @@ snippets:
         else
           echo "hugo config not found"
         fi
+#   _             _   _      _         _                        
+#  | |__   _  _  (_) | |  __| |  ___  | |_    _  _   __ _   ___ 
+#  | '_ \ | || | | | | | / _` | |___| | ' \  | || | / _` | / _ \
+#  |_.__/  \_,_| |_| |_| \__,_|       |_||_|  \_,_| \__, | \___/
+#                                                   |___/       
+  build-hugo: |
+    eval "$(clog Source project config)\n $(clog Crayon)" # setting & highlights
+    doPROD="$1"
+    modeMSG="$2"
+
+    ERR=0
+    clog Log -I "$STEP.$(((++s))).⚒️  build hugo  $modeMSG→$cF kodata/"
+
+    [ ! -d content ] && clog Log -E "$STEP.$(((++s))). no content/ folder" && exit 1
+    clog Log -I "$STEP.$(((++s))). purge$cF kodata/$cX, build site"
+    rm -rf kodata/*
+
+    opt="";[ -z "$doPROD" ]  && opt="$opt --buildDrafts --buildFuture --buildExpired"
+    clog Log -I "$STEP.$(((++s))). build hugo $modeMSG→${cF}kodata/$cC $opt"
+    hugo build --minify --logLevel info $opt
+  # ------------------------------------------------------------------------------
+  build-podserver: |
+    eval "$(clog Source project config)\n $(clog Crayon)" # setting & highlights
+    doPROD="$1"
+    modeMSG="$2"
+
+    ERR=0
+    clog Log -I "$STEP.$(((++s))).⚒️  build podserver $modeMSG→$cF tmp/"
+
+    help="tpl/help-golang.sh"    # build helpers
+    eval "$(clog Cat $help)"
+
+    fGoBuild tmp/podserver-amd-lnx     linux   amd64; ((ERR+=$?))
+    fGoBuild tmp/podserver-arm-lnx     linux   arm64; ((ERR+=$?))
+    fGoBuild tmp/podserver-arm-mac     darwin  arm64; ((ERR+=$?))
+    clog Log -B "$ERR" "$doPROD" "✅ build-podserver $modeMSG→$cS tmp/$cX ok" "❌ build-podserver  $modeMSG→$cE tmp/$cX failed" || exit 1; #abort if PROD
+  # ------------------------------------------------------------------------------
+  build-ko: |
+    eval "$(clog Source project config)\n $(clog Crayon)" # setting & highlights
+    doPROD="$1"
+    modeMSG="$2"
+
+    ERR=0
+    clog Log -I "$STEP.$(((++s))).⚒️  build ko $modeMSG→$cU hub.docker.com/$DOCKER_NS$cX"
+
+    [ -z "doPROD" ] && devTAG="-dev"
+    [ -n "$(clog bc-wants-stage-flow)" ]&& stageTAG="-stage"
+    
+    tag1="$(clog git tag ref)$devTAG" # 1.2.3 | 1.2.3-stage | 1.2.3-stage-dev
+    tag2="latest$stageTAG$devTAG"     # latest | latest-stage | latest-dev | latest-stage-dev
+
+    # config is in .ko.yaml
+    # use the default docker repo unless told otherwise
+    [ -z "$KO_DOCKER_REPO" ] && KO_DOCKER_REPO="$DOCKER_NS"
+    export KO_DOCKER_REPO                                      # push to repo
+    export KO_CONFIG_PATH=".ko.yaml"                           # build options
+    export KO_DATA_DATE_EPOCH=$(git log -1 --format='%ct')     # date on image
+
+    ko build --base-import-paths --tags "$tag1" --tags "$tag2" .
+    if [ $? -gt 0 ]; then
+      msg="ko build failed $cE $PROJECT$cX:$cW$tag1$cX and ${cW}$tag2"
+      clog Log -E "$msg"
+      printf "$msg" > /tmp/clog-notify
+      exit 1
+    fi
+    msg="multi-arch ko build$cF $PROJECT$cX:$cW$tag1$cX and ${cW}$tag2"
+    clog Log -S "$msg"
+    printf "$msg" > /tmp/clog-notify
+
+  build: |
+    export MAKE="hugo podserver ko"; [[ "MAKE" == "$1" ]] && MAKE="$2"
+    modeMSG="$(clog bc-prod-logic-build)"
+    [[ "${modeMSG:0:4}" == "prod" ]] && doPROD="prod"
+
+    eval "$(clog Source project config)\n $(clog Crayon)" # setting & highlight
+    clog Log -I  "🤖 build $modeMSG$cS $PROJECT$cX MAKE:$cC $MAKE"
+
+    ERR=0; export STEP=0
+    clog Log -I "$(((++STEP))).  Check pre-build"; clog Check pre-build; ERR=$((ERR+$?))
+    clog Log -I "$(((++STEP))).  Check build";     clog Check build;     ERR=$((ERR+$?))
+    clog Log -B "$ERR" "$doPROD" "✅ checks ok" "❌ checks failed" || exit 1; #abort if PROD
+    clog bc-logs-hr
+
+    ((STEP++));clog Should MAKE "hugo"      && clog build-hugo      "$doPROD" "$modeMSG" && clog bc-logs-hr || exit 1
+    ((STEP++));clog Should MAKE "podserver" && clog build-podserver "$doPROD" "$modeMSG" && clog bc-logs-hr || exit 1
+    ((STEP++));clog Should MAKE "ko"        && clog build-ko        "$doPROD" "$modeMSG" && clog bc-logs-hr || exit 1
+    icon="✅";[ $ERR -gt 0 ] && icon="❌"
+    printf -v MSG "$icon build $modeMSG complete with %d errors" $ERR
+    echo "$modeMSG" > "$(clog workflow-message-file)"
+    clog Log -B "$ERR" "$doPROD" "✅ golang build ok - $modeMSG" "❌ golang build failed - $modeMSG" || exit 1; #abort if PROD
+    exit 0
 # =============================================================================
 #    ___   _                 _
 #   / __| | |_    ___   __  | |__
@@ -158,7 +204,7 @@ check:
     blocks:
       - name: wsl Zone.Identifier files
         try: |
-          [ -n "$(find . -name '*Zone.Identifier')" ] && exit 1
+          [ -n "$(find . -name '*Zone.Identifier')" ] && exit 1 || exit 0
         catch: |
           eval "$(clog Crayon)"
           n=$(find . -name '*Zone.Identifier'|wc -l)
